name: WaystoneWarps
version: 1.0.0
api-version: '1.21'
main: dev.mizarc.waystonewarps.WaystoneWarps
libraries:
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.9.0
  - org.jetbrains.kotlin:kotlin-stdlib:2.3.0
  - io.insert-koin:koin-core-jvm:4.1.1
  - com.zaxxer:HikariCP:7.0.2
  - me.xdrop:fuzzywuzzy:1.3.1
permissions:
  waystonewarps.command.warpmenu:
    description: Allows access to the warp menu command
    default: true

  waystonewarps.bypass.*:
    description: Full control of all waystones
    default: op
    children:
      waystonewarps.bypass.access_control: true
      waystonewarps.bypass.manage_players: true
      waystonewarps.bypass.rename: true
      waystonewarps.bypass.icon: true
      waystonewarps.bypass.relocate: true
      waystonewarps.bypass.open_menu: true
      waystonewarps.create: true

  waystonewarps.create:
    description: Allows creating waystone warps
    default: true
    
  waystonewarps.discover:
    description: Allows discovering waystone warps
    default: true

  waystonewarps.bypass.access_control:
    description: Can change any waystone to private or public
    default: op

  waystonewarps.bypass.manage_players:
    description: Can manage whitelist on other waystones
    default: op

  waystonewarps.bypass.rename:
    description: Can rename other waystones
    default: op

  waystonewarps.bypass.icon:
    description: Can change other waystone icons
    default: op

  waystonewarps.bypass.relocate:
    description: Can move any waystone
    default: op

  waystonewarps.bypass.open_menu:
    description: Can open other players' waystone menus
    default: op

  waystonewarps.admin.invalids.*:
    description: Access to all invalid warp management commands
    default: op
    children:
      waystonewarps.admin.invalids.list: true
      waystonewarps.admin.invalids.remove: true
      waystonewarps.admin.invalids.removeall: true

  waystonewarps.admin.invalids.list:
    description: Allows listing warps in invalid worlds
    default: op

  waystonewarps.admin.invalids.remove:
    description: Allows removing warps from specific invalid worlds
    default: op

  waystonewarps.admin.invalids.removeall:
    description: Allows removing all warps from all invalid worlds
    default: op

  waystonewarps.teleport:
    description: Allows teleportation to waystones
    default: true

  waystonewarps.teleport.interworld:
    description: Allows teleportation between different worlds
    default: op

  waystonewarps.teleport.cooldown_bypass:
    description: Bypasses the cooldown between teleportations
    default: op